# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

betaToMaxCpp <- function(kU, kY, kBeta, kLambda, kX, kZ) {
    .Call('mnmcem_betaToMaxCpp', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ)
}

lambdaMaxCpp <- function(kU) {
    .Call('mnmcem_lambdaMaxCpp', PACKAGE = 'mnmcem', kU)
}

loglikelihoodCpp <- function(kU, kY, kBeta, kLambda, kX, kZ) {
    .Call('mnmcem_loglikelihoodCpp', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ)
}

logRatioCpp <- function(kU, kY, kBeta, kLambda, kX, kZ) {
    .Call('mnmcem_logRatioCpp', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ)
}

qFunction2 <- function(kU, kY, kBeta, kLambda, kX, kZ) {
    .Call('mnmcem_qFunction2', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ)
}

qFunctionCpp <- function(kU, kY, kBeta, kLambda, kX, kZ) {
    .Call('mnmcem_qFunctionCpp', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ)
}

rcpp_hello_world <- function() {
    .Call('mnmcem_rcpp_hello_world', PACKAGE = 'mnmcem')
}

uSamplerCpp <- function(kU, kY, kBeta, kLambda, kX, kZ, B, kC0) {
    .Call('mnmcem_uSamplerCpp', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ, B, kC0)
}

uSamplerRWCpp <- function(kU, kY, kBeta, kLambda, kX, kZ, B, sd) {
    .Call('mnmcem_uSamplerRWCpp', PACKAGE = 'mnmcem', kU, kY, kBeta, kLambda, kX, kZ, B, sd)
}

